-- ElectoStock database (Supabase / Postgres 15+).
--
-- Everything the old Apps Script backend did lives here:
--   * roles and permissions  → profiles + row-level security (RLS) policies
--   * BOM cost rollups       → triggers on items / bom_lines
--   * BOM validation         → constraints + a cycle-check trigger
--   * checkout               → checkout(), one transaction
--   * user admin             → invites + admin_* functions
-- Tests: tests/db/*.test.mjs run this file against PGlite (see tests/db/harness.mjs).

-- ─── Roles ───────────────────────────────────────────────────────────────────
-- viewer: read only · user: edit stock, BOMs, checkouts, categories · admin: also
-- delete items/categories and manage users.

create table public.profiles (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  email      text not null,
  role       text not null default 'viewer' check (role in ('viewer', 'user', 'admin')),
  created_at timestamptz not null default now()
);

-- Accounts can only be created for invited emails (see handle_new_user).
create table public.invites (
  email      text primary key check (email = lower(email)),
  role       text not null check (role in ('viewer', 'user', 'admin')),
  invited_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create function public.role_rank(r text) returns int
language sql immutable as $$
  select case r when 'viewer' then 0 when 'user' then 1 when 'admin' then 2 else -1 end
$$;

-- Role of the signed-in caller, or 'none'. Security definer so policies can use
-- it without granting everyone read access to profiles.
create function public.my_role() returns text
language sql stable security definer set search_path = public as $$
  select coalesce((select role from public.profiles where user_id = auth.uid()), 'none')
$$;

create function public.has_role(min_role text) returns boolean
language sql stable as $$
  select public.role_rank(public.my_role()) >= public.role_rank(min_role)
$$;

-- New auth user → profile with the invited role. Uninvited sign-ups are rejected.
create function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  inv public.invites;
begin
  select * into inv from public.invites where email = lower(new.email);
  if not found then
    raise exception 'The email % has not been invited', new.email using errcode = 'P0001';
  end if;
  insert into public.profiles (user_id, email, role) values (new.id, lower(new.email), inv.role);
  delete from public.invites where email = inv.email;
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- There must always be at least one admin.
create function public.keep_one_admin() returns trigger
language plpgsql as $$
begin
  if old.role = 'admin'
     and (tg_op = 'DELETE' or new.role <> 'admin')
     and (select count(*) from public.profiles where role = 'admin') <= 1 then
    raise exception 'There must be at least one admin' using errcode = 'P0001';
  end if;
  return coalesce(new, old);
end $$;

create trigger profiles_keep_one_admin
  before update of role or delete on public.profiles
  for each row execute function public.keep_one_admin();

-- ─── Inventory ───────────────────────────────────────────────────────────────

create table public.categories (
  name  text primary key check (btrim(name) <> ''),
  color text not null default '#78716c'
);

-- ids are "by default" so the import can keep the old sheet ids.
create table public.items (
  id            bigint generated by default as identity primary key,
  part          text    not null default '',
  name          text    not null check (btrim(name) <> ''),
  category      text    not null default '',
  qty           numeric not null default 0 check (qty >= 0),
  min           numeric not null default 0,
  location      text    not null default '',
  unit_cost     numeric not null default 0,
  supplier      text    not null default '',
  supplier_part text    not null default '',
  notes         text    not null default '',
  updated_at    timestamptz not null default now()
);

-- quantity may be negative (cancels parts added elsewhere in the tree, or returns
-- them to stock at checkout) but never zero.
create table public.bom_lines (
  parent_id bigint  not null references public.items(id) on delete cascade,
  child_id  bigint  not null references public.items(id) on delete cascade,
  quantity  numeric not null check (quantity <> 0),
  primary key (parent_id, child_id),
  check (parent_id <> child_id)
);
create index bom_lines_child_idx on public.bom_lines (child_id);

-- History is denormalised on purpose: it must survive later item and BOM edits.
create table public.checkout_log (
  id                      bigint generated by default as identity primary key,
  created_at              timestamptz not null default now(),
  job_name                text    not null,
  assembly_id             bigint  not null,
  assembly_name           text    not null,
  qty_built               numeric not null,
  component_name          text    not null,
  component_supplier_part text    not null default '',
  component_location      text    not null default '',
  qty_deducted            numeric not null,
  sub_assembly_name       text    not null default '',
  depth                   int     not null default 0,
  user_email              text    not null default ''
);
create index checkout_log_assembly_idx on public.checkout_log (assembly_id, created_at desc);

-- ─── BOM math ────────────────────────────────────────────────────────────────

-- Cost of one unit, always recalculated from leaf unit_costs.
create function public.bom_cost(p_id bigint) returns numeric
language sql stable set search_path = public as $$
  with recursive tree (child_id, mult, path) as (
    select child_id, quantity, array[parent_id]
    from bom_lines where parent_id = p_id
    union all
    select b.child_id, t.mult * b.quantity, t.path || b.parent_id
    from tree t join bom_lines b on b.parent_id = t.child_id
    where not b.parent_id = any (t.path)                       -- cycle guard
  )
  select coalesce(sum(t.mult * i.unit_cost), 0)
  from tree t join items i on i.id = t.child_id
  where not exists (select 1 from bom_lines x where x.parent_id = t.child_id)  -- leaves only
$$;

-- Every assembly that contains any of p_ids anywhere in its tree.
create function public.bom_ancestors(p_ids bigint[]) returns setof bigint
language sql stable set search_path = public as $$
  with recursive up (id) as (
    select parent_id from bom_lines where child_id = any (p_ids)
    union
    select b.parent_id from up join bom_lines b on b.child_id = up.id
  )
  select id from up
$$;

-- A BOM line P→C creates a cycle if P is already inside C's tree.
create function public.bom_prevent_cycles() returns trigger
language plpgsql as $$
begin
  if exists (
    with recursive down (id) as (
      select child_id from public.bom_lines where parent_id = new.child_id
      union
      select b.child_id from down join public.bom_lines b on b.parent_id = down.id
    )
    select 1 from down where id = new.parent_id
  ) then
    raise exception '"%" already contains this assembly',
      (select name from public.items where id = new.child_id) using errcode = 'P0001';
  end if;
  return new;
end $$;

create trigger bom_lines_prevent_cycles
  before insert or update on public.bom_lines
  for each row execute function public.bom_prevent_cycles();

-- ─── Cost rollups ────────────────────────────────────────────────────────────
-- An assembly's unit_cost is derived: whenever its row is written, it is
-- recalculated from its BOM. A cost change on any item then "touches" its direct
-- parents, which recalculate in turn, all the way up (the BOM graph has no cycles).
-- An item without BOM lines keeps its manually entered cost.

create function public.items_before_write() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  if tg_op = 'UPDATE' and exists (select 1 from public.bom_lines where parent_id = new.id) then
    new.unit_cost := public.bom_cost(new.id);
  end if;
  return new;
end $$;

create trigger items_before_write
  before insert or update on public.items
  for each row execute function public.items_before_write();

create function public.items_after_cost_change() returns trigger
language plpgsql as $$
begin
  update public.items set unit_cost = unit_cost      -- before-trigger recalculates
  where id in (select parent_id from public.bom_lines where child_id = new.id);
  return null;
end $$;

create trigger items_after_cost_change
  after update of unit_cost on public.items
  for each row when (old.unit_cost is distinct from new.unit_cost)
  execute function public.items_after_cost_change();

create function public.bom_lines_after_change() returns trigger
language plpgsql as $$
begin
  update public.items set unit_cost = unit_cost
  where id = coalesce(new.parent_id, old.parent_id);
  return null;
end $$;

create trigger bom_lines_after_change
  after insert or update or delete on public.bom_lines
  for each row execute function public.bom_lines_after_change();

-- ─── Actions ─────────────────────────────────────────────────────────────────

-- Stock adjustment, atomic on the server. p_action: add | remove | set.
create function public.adjust_qty(p_id bigint, p_action text, p_qty numeric)
returns numeric language plpgsql set search_path = public as $$
declare
  result numeric;
begin
  if not public.has_role('user') then
    raise exception 'Your role is not allowed to do that' using errcode = '42501';
  end if;
  if p_action not in ('add', 'remove', 'set') then
    raise exception 'Unknown adjustment: %', p_action using errcode = 'P0001';
  end if;
  update items set qty = case p_action
      when 'add'    then qty + coalesce(p_qty, 0)
      when 'remove' then greatest(0, qty - coalesce(p_qty, 0))
      else greatest(0, coalesce(p_qty, 0)) end
  where id = p_id
  returning qty into result;
  if not found then
    raise exception 'Item not found: %', p_id using errcode = 'P0002';
  end if;
  return result;
end $$;

-- Replace all BOM lines of one assembly. p_lines: [{child_id, quantity}, …]
-- Costs of this assembly and everything above it update through the triggers.
-- Returns the new unit_cost of every affected assembly: [{id, unit_cost}, …]
create function public.save_bom(p_parent_id bigint, p_lines jsonb)
returns jsonb language plpgsql set search_path = public as $$
declare
  line jsonb;
  seen bigint[] := '{}';
  child bigint;
  q numeric;
begin
  if not public.has_role('user') then
    raise exception 'Your role is not allowed to do that' using errcode = '42501';
  end if;
  if not exists (select 1 from items where id = p_parent_id) then
    raise exception 'Assembly not found: %', p_parent_id using errcode = 'P0002';
  end if;
  for line in select * from jsonb_array_elements(coalesce(p_lines, '[]'::jsonb)) loop
    child := (line ->> 'child_id')::bigint;
    q     := (line ->> 'quantity')::numeric;
    if q is null or q = 0 or q = 'NaN' then
      raise exception 'Every quantity must be a number other than 0' using errcode = 'P0001';
    end if;
    if child = p_parent_id then
      raise exception 'An assembly cannot contain itself' using errcode = 'P0001';
    end if;
    if child = any (seen) then
      raise exception 'Duplicate components — each item can only appear once.' using errcode = 'P0001';
    end if;
    if not exists (select 1 from items where id = child) then
      raise exception 'Component not found: %', child using errcode = 'P0002';
    end if;
    seen := seen || child;
  end loop;

  delete from bom_lines where parent_id = p_parent_id;
  insert into bom_lines (parent_id, child_id, quantity)
  select p_parent_id, (l ->> 'child_id')::bigint, (l ->> 'quantity')::numeric
  from jsonb_array_elements(coalesce(p_lines, '[]'::jsonb)) l;

  return coalesce((
    select jsonb_agg(jsonb_build_object('id', id, 'unit_cost', unit_cost))
    from items
    where id = p_parent_id or id in (select public.bom_ancestors(array[p_parent_id]))
  ), '[]'::jsonb);
end $$;

-- Build p_qty_built units of an assembly in one transaction: resolve its BOM to
-- leaf components, apply each component's net change and write the log.
-- A net can be positive (deducted, floored at 0), zero (untouched) or negative
-- (returned to stock). The log keeps one row per path, including negative ones.
-- Security definer: the log can only be written through this function.
create function public.checkout(p_assembly_id bigint, p_qty_built numeric, p_job_name text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  asm items;
  who text;
  rows_written int;
  results jsonb;
begin
  if not public.has_role('user') then
    raise exception 'Your role is not allowed to do that' using errcode = '42501';
  end if;
  if coalesce(btrim(p_job_name), '') = '' then
    raise exception 'job_name required' using errcode = 'P0001';
  end if;
  if p_qty_built is null or p_qty_built < 1 or p_qty_built <> trunc(p_qty_built) then
    raise exception 'qty_built must be a whole number of at least 1' using errcode = 'P0001';
  end if;
  select * into asm from items where id = p_assembly_id;
  if not found then
    raise exception 'Assembly not found: %', p_assembly_id using errcode = 'P0002';
  end if;
  if not exists (select 1 from bom_lines where parent_id = p_assembly_id) then
    raise exception '"%" has no BOM', asm.name using errcode = 'P0001';
  end if;
  select email into who from profiles where user_id = auth.uid();

  create temporary table co_leaves on commit drop as
  with recursive tree (child_id, qty, path, depth, visited) as (
    select b.child_id, b.quantity * p_qty_built, asm.name, 0, array[b.parent_id]
    from bom_lines b where b.parent_id = p_assembly_id
    union all
    select b.child_id, t.qty * b.quantity, t.path || ' > ' || i.name, t.depth + 1, t.visited || b.parent_id
    from tree t
    join items i on i.id = t.child_id
    join bom_lines b on b.parent_id = t.child_id
    where not b.parent_id = any (t.visited)
  )
  select t.child_id, t.qty, t.path, t.depth
  from tree t
  where not exists (select 1 from bom_lines x where x.parent_id = t.child_id);

  insert into checkout_log (job_name, assembly_id, assembly_name, qty_built, component_name,
                            component_supplier_part, component_location, qty_deducted,
                            sub_assembly_name, depth, user_email)
  select btrim(p_job_name), asm.id, asm.name, p_qty_built, i.name, i.supplier_part, i.location,
         l.qty, l.path, l.depth, coalesce(who, '')
  from co_leaves l join items i on i.id = l.child_id
  order by l.depth, l.path, i.name;
  get diagnostics rows_written = row_count;

  with net as (
    select child_id, sum(qty) as qty from co_leaves group by child_id having sum(qty) <> 0
  ), changed as (
    update items i set qty = greatest(0, i.qty - net.qty)
    from net where i.id = net.child_id
    returning i.id, i.qty
  )
  select coalesce(jsonb_agg(jsonb_build_object('id', id, 'newQty', qty) order by id), '[]'::jsonb)
  into results from changed;

  drop table co_leaves;
  return jsonb_build_object('success', true, 'results', results, 'rows_written', rows_written);
end $$;

-- ─── User admin ──────────────────────────────────────────────────────────────
-- Inviting: admin_invite() records the email and role; the app then asks Supabase
-- Auth to email that person a sign-in link. Their account is created (with the
-- invited role) the moment Supabase registers them.

create function public.require_admin() returns void
language plpgsql stable as $$
begin
  if not public.has_role('admin') then
    raise exception 'Only admins can manage users' using errcode = '42501';
  end if;
end $$;

create function public.admin_list_users()
returns table (user_id uuid, email text, role text, is_self boolean, pending boolean,
               last_sign_in_at timestamptz)
language plpgsql stable security definer set search_path = public as $$
begin
  perform public.require_admin();
  return query
    select p.user_id, p.email, p.role, p.user_id = auth.uid(), false, u.last_sign_in_at
    from profiles p join auth.users u on u.id = p.user_id
    union all
    select null::uuid, i.email, i.role, false, true, null::timestamptz from invites i
    order by 2;
end $$;

create function public.admin_invite(p_email text, p_role text) returns void
language plpgsql security definer set search_path = public as $$
declare
  e text := lower(btrim(p_email));
begin
  perform public.require_admin();
  if e !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'Enter a valid email address' using errcode = 'P0001';
  end if;
  if public.role_rank(p_role) < 0 then
    raise exception 'Role must be viewer, user or admin' using errcode = 'P0001';
  end if;
  if exists (select 1 from profiles where email = e) then
    raise exception '% already has an account', e using errcode = 'P0001';
  end if;
  insert into invites (email, role, invited_by) values (e, p_role, auth.uid())
  on conflict (email) do update set role = excluded.role, invited_by = excluded.invited_by, created_at = now();
end $$;

create function public.admin_cancel_invite(p_email text) returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public.require_admin();
  delete from invites where email = lower(btrim(p_email));
end $$;

create function public.admin_set_role(p_user_id uuid, p_role text) returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public.require_admin();
  if p_user_id = auth.uid() then
    raise exception 'You can''t change your own role. Ask another admin to do it.' using errcode = 'P0001';
  end if;
  if public.role_rank(p_role) < 0 then
    raise exception 'Role must be viewer, user or admin' using errcode = 'P0001';
  end if;
  update profiles set role = p_role where user_id = p_user_id;
  if not found then
    raise exception 'User not found' using errcode = 'P0002';
  end if;
end $$;

-- Deleting the auth user removes the profile too; their sessions stop working
-- at once because every policy checks the profile.
create function public.admin_delete_user(p_user_id uuid) returns void
language plpgsql security definer set search_path = public, auth as $$
begin
  perform public.require_admin();
  if p_user_id = auth.uid() then
    raise exception 'You can''t delete your own account.' using errcode = 'P0001';
  end if;
  delete from auth.users where id = p_user_id;
  if not found then
    raise exception 'User not found' using errcode = 'P0002';
  end if;
end $$;

-- ─── Row-level security ──────────────────────────────────────────────────────

alter table public.profiles     enable row level security;
alter table public.invites      enable row level security;
alter table public.categories   enable row level security;
alter table public.items        enable row level security;
alter table public.bom_lines    enable row level security;
alter table public.checkout_log enable row level security;

create policy "read own profile" on public.profiles for select to authenticated
  using (user_id = auth.uid());

create policy "read"   on public.categories for select to authenticated using ((select public.has_role('viewer')));
create policy "add"    on public.categories for insert to authenticated with check ((select public.has_role('user')));
create policy "edit"   on public.categories for update to authenticated using ((select public.has_role('user'))) with check ((select public.has_role('user')));
create policy "delete" on public.categories for delete to authenticated using ((select public.has_role('admin')));

create policy "read"   on public.items for select to authenticated using ((select public.has_role('viewer')));
create policy "add"    on public.items for insert to authenticated with check ((select public.has_role('user')));
create policy "edit"   on public.items for update to authenticated using ((select public.has_role('user'))) with check ((select public.has_role('user')));
create policy "delete" on public.items for delete to authenticated using ((select public.has_role('admin')));

create policy "read"   on public.bom_lines for select to authenticated using ((select public.has_role('viewer')));
create policy "add"    on public.bom_lines for insert to authenticated with check ((select public.has_role('user')));
create policy "edit"   on public.bom_lines for update to authenticated using ((select public.has_role('user'))) with check ((select public.has_role('user')));
create policy "delete" on public.bom_lines for delete to authenticated using ((select public.has_role('user')));

create policy "read" on public.checkout_log for select to authenticated using ((select public.has_role('viewer')));
-- No insert/update/delete policies: the log is written only by checkout().

-- invites: no policies; only the security-definer admin_* functions touch it.

-- ─── Grants ──────────────────────────────────────────────────────────────────
-- Supabase grants broad table access to anon/authenticated by default; RLS above
-- decides. Functions: nothing for anon, and only the app's entry points for users.

revoke all on all tables    in schema public from anon;
revoke all on all functions in schema public from public, anon;
grant select, insert, update, delete on public.categories, public.items, public.bom_lines to authenticated;
grant select on public.checkout_log, public.profiles to authenticated;
grant execute on function
  public.adjust_qty(bigint, text, numeric),
  public.save_bom(bigint, jsonb),
  public.checkout(bigint, numeric, text),
  public.admin_list_users(),
  public.admin_invite(text, text),
  public.admin_cancel_invite(text),
  public.admin_set_role(uuid, text),
  public.admin_delete_user(uuid),
  public.bom_cost(bigint),
  public.my_role(),
  public.has_role(text),
  public.role_rank(text),
  public.require_admin(),
  public.bom_ancestors(bigint[])
  to authenticated;

-- ─── Realtime ────────────────────────────────────────────────────────────────
-- Open tabs get changes pushed instead of polling. The publication only exists
-- on Supabase; skipped elsewhere (tests).
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.items, public.bom_lines, public.categories;
  end if;
end $$;
