-- Barcode scanning and a log of single-item stock changes.
--
--   * items.barcode: a code linked to an item by hand (a scanned label that matched
--     nothing). Scans also match supplier_part and part, and the app's own labels
--     carry the item id, so most items never need one.
--   * stock_moves: one row per check in / check out / set, with who and why.
--     Written only by adjust_stock(), the same way checkout_log is written only by
--     checkout(). BOM checkouts stay in checkout_log.

alter table public.items add column barcode text not null default '';

-- One item per code; blank means "none". Compared without surrounding spaces.
create unique index items_barcode_idx on public.items (btrim(barcode)) where btrim(barcode) <> '';

-- Denormalised like checkout_log, so the history survives the item being renamed
-- or deleted.
create table public.stock_moves (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  item_id       bigint,
  item_name     text    not null,
  supplier_part text    not null default '',
  location      text    not null default '',
  action        text    not null check (action in ('add', 'remove', 'set')),
  qty_requested numeric not null,
  qty_change    numeric not null,          -- the actual change, after flooring at 0
  qty_after     numeric not null,
  note          text    not null default '',
  user_email    text    not null default ''
);
create index stock_moves_created_idx on public.stock_moves (created_at desc);
create index stock_moves_item_idx on public.stock_moves (item_id, created_at desc);

alter table public.stock_moves enable row level security;
create policy "read" on public.stock_moves for select to authenticated using ((select public.has_role('viewer')));
-- No insert/update/delete policies: the log is written only by adjust_stock().

-- Stock adjustment with a log entry, atomic on the server. p_action: add | remove | set.
-- Security definer so it can write the log; it checks the caller's role itself.
create function public.adjust_stock(p_id bigint, p_action text, p_qty numeric, p_note text)
returns numeric language plpgsql security definer set search_path = public as $$
declare
  before_qty numeric;
  it items;
  who text;
begin
  if not public.has_role('user') then
    raise exception 'Your role is not allowed to do that' using errcode = '42501';
  end if;
  if p_action not in ('add', 'remove', 'set') then
    raise exception 'Unknown adjustment: %', p_action using errcode = 'P0001';
  end if;
  if p_qty is null or p_qty < 0 or p_qty = 'NaN' then
    raise exception 'Quantity must be 0 or more' using errcode = 'P0001';
  end if;
  select qty into before_qty from items where id = p_id for update;
  if not found then
    raise exception 'Item not found: %', p_id using errcode = 'P0002';
  end if;
  update items set qty = case p_action
      when 'add'    then qty + p_qty
      when 'remove' then greatest(0, qty - p_qty)
      else p_qty end
  where id = p_id
  returning * into it;
  select email into who from profiles where user_id = auth.uid();
  insert into stock_moves (item_id, item_name, supplier_part, location, action, qty_requested,
                           qty_change, qty_after, note, user_email)
  values (it.id, it.name, it.supplier_part, it.location, p_action, p_qty,
          it.qty - before_qty, it.qty, coalesce(btrim(p_note), ''), coalesce(who, ''));
  return it.qty;
end $$;

-- The page that is live while this migration runs still calls adjust_qty; route
-- it through adjust_stock so its changes are logged too. Remove it in a later
-- release, once no page calls it.
create or replace function public.adjust_qty(p_id bigint, p_action text, p_qty numeric)
returns numeric language sql set search_path = public as $$
  select public.adjust_stock(p_id, p_action, coalesce(p_qty, 0), '')
$$;

-- Supabase's default privileges give new tables and functions to anon as well
revoke all on public.stock_moves from anon, authenticated;
revoke all on function public.adjust_stock(bigint, text, numeric, text) from public, anon;
grant select on public.stock_moves to authenticated;
grant execute on function public.adjust_stock(bigint, text, numeric, text) to authenticated;
